### PR TITLE
Support iterables per ECMAScript 2015 spec.

### PR DESCRIPTION
**Pull request by barberboy**
In addition to "array like" elements, the ECMAScript specification published June 2015 also supports "iterable" elements (see issue #2) that have a Symbol.iterator property.

This commit adds support for iterable elements, closely matching the steps outlined at http://www.ecma-international.org/ecma-262/6.0/#sec-array.from

A notable omission, however, is support for calling "[IteratorClose](http://www.ecma-international.org/ecma-262/6.0/#sec-iteratorclose)" in case of "[abrupt completion](http://www.ecma-international.org/ecma-262/6.0/#sec-completion-record-specification-type)" if an error is thrown by the mapping function. It'd be lovely to implement support for that as well at some point.

TODO: Add tests for Iterator support.

### CODE REVIEW

**Comment by tomek-he-him** [comment]
Hi Ben, thanks a lot for your contribution. It all looks great to me.

Would you be willing to add tests for the new functionality?

**Comment by barberboy** [comment]
Sure—I can't today but I'll try to get to it soon.

Since most environments that shim Symbol.iterator for Arrays/Sets/Maps also shim Array.from, you have to be a bit careful with the tests to ensure that our polyfill is being used.

**Comment by tomek-he-him** [comment]
Thanks, that would be awesome!

By the way, this is not a classical polyfill – but just a CommonJS module modelled after the spec. So `require('array-from')` works even if the environment supports `Array.from` natively. Some refer to that as a ponyfill – and I guess that name came from @sindresorhus.

**Comment by barberboy** [comment]
Alright, tests have been added and are passing.

I moved the polyfill implementation into it's own file—arrayFrom.js—so that test.js could require it and be certain to test it instead of the actual `Array.from` when it's available. You may not like that, and you're welcome to change it back if you want :)

I also added support for the ["@@iterator" property that Gecko used](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/%40%40iterator#Browser_compatibility) for a bit to allow `Array.from` to be used in environments where `Symbol.iterator` is not yet supported. Again, you are welcome to remove that if you'd rather it not be there.

**Comment by tomek-he-him** [comment]
@barberboy thanks for the awesome, high-quality contribution!

I’ve left a few comments here and there – if you’d be so kind to fix those – or just say “I don’t think you’re right” – that would be even more awesome.

**Comment by barberboy** [comment]
I think I've fixed the issues you mentioned. Let me know if there are additional changes you'd like to see.

Just as a heads up, test coverage may appear to go down in Node.js v0.10.x environments. The test coverage is also checking for executed lines in `test.js`, and there are two conditional tests for using the native `Map` and `Set` if they exist. You could probably rewrite the test to get back to 100% coverage, but I didn't bother. `pollyfill.js` has 100% coverage for lines.

**Comment by tomek-he-him** [comment]
@ljharb, thanks for your comments :) Both definitely make sense.

@barberboy, thanks for the fixes :) If you still feel like fixing things @ljharb mentioned, that would be great. If not, I can also do it myself.

**Comment by barberboy** [comment]
Hey, @tomekwi, I'm not able to work on this right now, but I can pick it up a bit later if this is still open awhile.

The change itself is easy but it's a bit tricky to test it appropriately.

**Comment by tomek-he-him** [comment]
Take it easy, there’s no hurry. If I or someone else needs this before that, they can pick up the PR.

**Comment by tomek-he-him** [comment]
For the record:

There’s a proposal for a consistent API standard for polyfills, by @ljharb: https://github.com/es-shims/es-shim-api.

**Comment by tomek-he-him** [comment]
Hi @barberboy, I decided to merge your changes as they are – and split the proposed changes out to separate issues. (See above). At the moment I don’t have the time to tackle these – I’ll come back to this later. But if case you could and wanted help, that’d be great.

Thanks again for your rewrite!

**Comment by tomek-he-him** [comment]
Released in _v2.0.0_.

**Pull request merged**
