### PR TITLE
Link to ponyfill explanation

### PR DESCRIPTION
**Pull request by sindresorhus**
https://ponyfill.com

I coined the term `ponyfill`, and was finally able to create a page for it.

### CODE REVIEW

**Comment by sindresorhus** [comment]
ping

**Comment by tomek-he-him** [comment]
Hey @sindresorhus I’d love to merge this but I’m no longer a contributor at studio-b12. 

cc @bck2207

**Comment by tomek-he-him** [comment]
Thanks so much for this by the way, and sorry for not taking action back then. Posting a gif but not merging, weird 😄

**Pull request closed without merging**
